"""
Chart-pack access control.

The chart packs are generated by ghost/chartsite into data/packs/*.json and were
previously served as static files from Netlify, which meant the "Members" label in the
coverage matrix was decoration: anyone who read manifest.js could fetch the JSON
directly. Serving them from here instead puts them behind the same Ghost tier check
the data API already uses, so one gate covers both.

Tiers, in ascending order:

    public   two shop-window packs, no account needed
    daily    every region-* pack, for "Daily" subscribers and above
    premium  all 55 packs, for "Daily + Data" and "East Asia"

The ranking is inclusive — a premium member reaches everything below them.
"""
import json
import os
from pathlib import Path
from typing import Optional

# Where the generated packs live. Set PACKS_DIR to point at a checkout of
# ghost/chartsite/data/packs, or sync them in with scripts/sync_packs.py.
PACKS_DIR = Path(os.environ.get(
    'PACKS_DIR', Path(__file__).parent / 'packs'
)).expanduser()

# The two packs that stay open. Override with PUBLIC_PACKS="cn-macro,jp-macro".
PUBLIC_PACKS = set(
    p.strip() for p in os.environ.get('PUBLIC_PACKS', 'cn-macro,jp-macro').split(',')
    if p.strip()
)

# Economy prefix whose packs are released at the Daily tier.
DAILY_PREFIX = os.environ.get('DAILY_PREFIX', 'region')

# Ghost tiers map onto these via api._determine_tier: free members and anonymous
# visitors rank 0, "Daily" ranks 1, "Daily + Data" / "East Asia" / comped rank 2.
TIER_RANK = {
    'public': 0,
    'free': 0,
    'daily': 1,
    'premium': 2,
}

TIER_LABEL = {
    'public': 'Open',
    'daily': 'Daily',
    'premium': 'Daily + Data',
}


def required_tier(pack_id: str) -> str:
    """Lowest tier that may read this pack."""
    if pack_id in PUBLIC_PACKS:
        return 'public'
    if pack_id.split('-', 1)[0] == DAILY_PREFIX:
        return 'daily'
    return 'premium'


def rank(tier: Optional[str]) -> int:
    """Rank of a user tier. Unknown or missing tiers get the floor, not the ceiling."""
    return TIER_RANK.get((tier or 'free').lower(), 0)


def can_read(pack_id: str, user_tier: Optional[str]) -> bool:
    return rank(user_tier) >= TIER_RANK[required_tier(pack_id)]


def pack_path(pack_id: str) -> Optional[Path]:
    """Resolve a pack id to a file, refusing anything that escapes PACKS_DIR."""
    if not pack_id or '/' in pack_id or '\\' in pack_id or pack_id.startswith('.'):
        return None
    p = (PACKS_DIR / f'{pack_id}.json').resolve()
    try:
        p.relative_to(PACKS_DIR.resolve())
    except ValueError:                      # traversal attempt
        return None
    return p if p.is_file() else None


def list_packs() -> list:
    """Every pack on disk with the tier it needs. Safe to serve unauthenticated —
    it is the catalogue, not the contents, and the site needs it to draw the locks."""
    if not PACKS_DIR.is_dir():
        return []
    out = []
    for f in sorted(PACKS_DIR.glob('*.json')):
        pid = f.stem
        economy, _, pack = pid.partition('-')
        tier = required_tier(pid)
        out.append({
            'id': pid,
            'economy': economy,
            'pack': pack,
            'required_tier': tier,
            'label': TIER_LABEL[tier],
            'bytes': f.stat().st_size,
        })
    return out


def load_pack(pack_id: str) -> Optional[dict]:
    p = pack_path(pack_id)
    if p is None:
        return None
    with open(p, encoding='utf-8') as fh:
        return json.load(fh)
